// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mergeSort
NumericVector mergeSort(NumericVector x);
RcppExport SEXP _algovis_mergeSort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mergeSort(x));
    return rcpp_result_gen;
END_RCPP
}
// mergeSortSnapshot
DataFrame mergeSortSnapshot(NumericVector x);
RcppExport SEXP _algovis_mergeSortSnapshot(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mergeSortSnapshot(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_algovis_mergeSort", (DL_FUNC) &_algovis_mergeSort, 1},
    {"_algovis_mergeSortSnapshot", (DL_FUNC) &_algovis_mergeSortSnapshot, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_algovis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
