# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mergeSort <- function(x) {
    .Call(`_algovis_mergeSort`, x)
}

mergeSortSnapshot <- function(x) {
    .Call(`_algovis_mergeSortSnapshot`, x)
}

